### ISSUE TITLE
cannot run printf in the test_program.c

### ISSUE THREAD

**Issue by chungen0126** [devbored/rISA#3]
I add a printf in the test_program.c, it can't find the c library. 
![Screenshot from 2022-01-18 00-21-55](https://user-images.githubusercontent.com/65023303/149806254-13ec955e-064a-4167-8304-a83bf6d98fa9.png)

**Comment by devbored** [comment]
Hi @chungen0126,

Also continuing from our offline email thread, the current example test program is built without libc

```Make
set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} -nostartfiles")
set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} -nostdlib")
```

You would need to remove these flags so that a libc implementation can be used (e.g. Newlib). Again, similar to #4 - you would also likely need to implement your own syscall "stubs" as well as implement your own rISA ecall handler library.

I am currently looking at working on another example to go inside the example folder to do a printf in rISA.

**Comment by devbored** [comment]
Hi @chungen0126,

I have recently added printf support in rISA:
```C
#include <stdio.h>

// Main program
int main(void) {
    printf("Hello World in rISA!\n");
    return 0;
}
```
Running in rISA:
```Bash
$ ./build/risa ./build/examples/hello_world/hello_world.hex
[rISA]: INFO  :       risa.c:165    :      setupSimulator : Interrupt period set to     [ 500 cycles ].
[rISA]: INFO  :       risa.c:166    :      setupSimulator : Virtual memory size set to  [ 1.000000 MB ].
[rISA]: INFO  :       risa.c:179    :       executionLoop : Running simulator...
===========================================================
Hello World in rISA!
===========================================================
[rISA]: INFO  :       risa.c:53     :    cleanupSimulator : Simulator stopping - time elapsed: [ 0.000268 seconds ].
```
Marking issue as resolved - thanks again for this suggestion/nudge! 👍
