### ISSUE TITLE
cannot goto a normal exit

### ISSUE THREAD

**Issue by chungen0126** [devbored/rISA#4]
I run risa to simula the test_program,and there is an infinite for loop. If I remove the for loop, then it goes wrong.
![Screenshot from 2022-01-18 00-16-22](https://user-images.githubusercontent.com/65023303/149806514-ee4d3140-fa31-491d-89e0-0ca57470835f.png)

**Comment by devbored** [comment]
Hi @chungen0126,

Continuing from our offline email thread, the issue here is that for my example RISC-V program, I do not use/link libc for the example as well as not use any libc start files. 

Because of this, I implemented my own start routine:
```C
// Begin user code execution here
void _start(void)
{
    // Define ptrs to access linker script variables
    uint32_t *pre_def_vals_ptr = &_etext;
    uint32_t *data_sec_ptr = &_sdata;
    uint32_t *bss_sec_ptr;

    // Copy data from LMA to VMA in the .data section
    if (pre_def_vals_ptr != data_sec_ptr)
        for (; data_sec_ptr < &_edata;)
            *data_sec_ptr++ = *pre_def_vals_ptr++;
    
    // Fill zeros in the .bss section
    for (bss_sec_ptr = &_sbss; bss_sec_ptr < &_ebss;)
        *bss_sec_ptr++ = 0;

    // Jump to the main program
    main();
}
```
If one tries to return from main, you can see here that the program counter will just run off and gets lost at that point.

To perform an exit on a return from main, one would need to implement an _exit syscall stub to then invoke ecall - a user would need to write a handler library to perform this in rISA (as the default handler is a nop).

This brings up an interesting idea of making the default ecall handler "do more" so that it implements at least the basic syscalls like read, write, exit, etc. So two things that I will look into:

1. Implement another example program (with implemented syscall stubs) doing a printf for example
2. Look at extending the default ecall handler to handle some basic syscalls

**Comment by chungen0126** [comment]
How do I use a test_handler in my test_program.

**Comment by devbored** [comment]
You can specify `-l <library_file>` to rISA to use handler functions from that library rather than the default ones.

Example: `./build/risa -l ./build/examples/test_handler/libtest_handler.so ...`

That `libtest_handler.so` is built when you build rISA - the code for that handler is here:
https://github.com/devbored/rISA/tree/main/examples/test_handler

**Comment by devbored** [comment]
Hi @chungen0126,

rISA now handles the `exit` syscall by:

- Reporting the return code if non-zero
- Cleans-up simulator
- Exiting

Marking this issue as resolved ✅
